# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cal_Hes <- function(XiM0, Covariate, parvec, len, XiM0_len) {
    .Call(`_LVHML_rcpp_cal_Hes`, XiM0, Covariate, parvec, len, XiM0_len)
}

rcpp_cal_Hes_foru <- function(XiM0, Covariate, parvec, len, XiM0_len, nonzero_ind) {
    .Call(`_LVHML_rcpp_cal_Hes_foru`, XiM0, Covariate, parvec, len, XiM0_len, nonzero_ind)
}

rcpp_cal_grad <- function(yvec, XiM0, Covariate, len, parlen) {
    .Call(`_LVHML_rcpp_cal_grad`, yvec, XiM0, Covariate, len, parlen)
}

rcpp_objpar_prep <- function(XiM, yvec, len) {
    .Call(`_LVHML_rcpp_objpar_prep`, XiM, yvec, len)
}

rcpp_xi_func <- function(x) {
    .Call(`_LVHML_rcpp_xi_func`, x)
}

rcpp_objprep <- function(Ymatlog, R, tU, Theta, X, Zmat, N, J, px, pz, u_len, K, Tp, ext, gamma_fix) {
    .Call(`_LVHML_rcpp_objprep`, Ymatlog, R, tU, Theta, X, Zmat, N, J, px, pz, u_len, K, Tp, ext, gamma_fix)
}

rcpp_getEforjEujXiM0 <- function(uj, indices_R, lengths_R, Theta, X, Zmat, N, Tp, K, px, pz, ujlen, ext, gamma_fix) {
    .Call(`_LVHML_rcpp_getEforjEujXiM0`, uj, indices_R, lengths_R, Theta, X, Zmat, N, Tp, K, px, pz, ujlen, ext, gamma_fix)
}

rcpp_proj_func <- function(out, K, proj_const) {
    .Call(`_LVHML_rcpp_proj_func`, out, K, proj_const)
}

rcpp_getnewpar_func <- function(XiM0, yvec, len, grad, drt, oldpar, Covariates, tooff, proj_const) {
    .Call(`_LVHML_rcpp_getnewpar_func`, XiM0, yvec, len, grad, drt, oldpar, Covariates, tooff, proj_const)
}

rcpp_getnewpar_func_foru <- function(XiM0, yvec, len, grad, drt, oldpar, Covariates, tooff, nonzero_ind, proj_const) {
    .Call(`_LVHML_rcpp_getnewpar_func_foru`, XiM0, yvec, len, grad, drt, oldpar, Covariates, tooff, nonzero_ind, proj_const)
}

rcpp_BetagetEforj <- function(indices_R, lengths_R, X, Zmat, N, Tp, px, pz, ext, gamma_fix) {
    .Call(`_LVHML_rcpp_BetagetEforj`, indices_R, lengths_R, X, Zmat, N, Tp, px, pz, ext, gamma_fix)
}

rcpp_BetaonlygetEforj <- function(indices_R, lengths_R, X, N, Tp, px, ext, gamma_fix) {
    .Call(`_LVHML_rcpp_BetaonlygetEforj`, indices_R, lengths_R, X, N, Tp, px, ext, gamma_fix)
}

